### ISSUE TITLE
Heli durability 

### ISSUE THREAD

**Issue by P3dru1233** [Zilox135/A21Modlets#3]
Sorry to bother you again Is there a way to lower heli durability? to be more balanced

and in another question do you make mods by demand if we payed you namely a capture and hold victory condition mod, if so how mutch do you think it could cost?

Best regards!

**Comment by Zilox135** [comment]
You can change the durability in the xml files if you really wanted to, although it's set high because you can damage yourself with the missiles. 

I don't do mod requests or take commissions for mods.
