### ISSUE TITLE
Null Reference Error

### ISSUE THREAD

**Issue by gogrady4117** [Zilox135/A21Modlets#4]
![image](https://github.com/Zilox135/A21Modlets/assets/34630802/81684973-4e81-4fc4-9424-55b860fd8c3e)

Getting Null Error reference repeatedly. A21.2 (b37) with all mods downloaded.

**Comment by Zilox135** [comment]
This usually means that one of the mods is missing or not installed correctly. If you attach your log file it will have more information.
